services:
  nginx:
    container_name: nginx
    build: ./services/nginx/
    ports:
      - 443:443
    expose:
      - 9000
    restart: on-failure
    networks:
      - my_network

networks:
  my_network:
    name: "my_network"